add Cannon
MRedor/JavaHW pull request #14
Opened 2019-05-21 13:13 UTC by MRedor

2019-05-31 11:58 UTC, RamSaw requested changes
@MRedor проверил.
-1 балл за нереализованную функциональность и грубо захардкоженные константы.

2019-05-31 11:58 UTC, RamSaw commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
jar не запускается

2019-05-31 11:58 UTC, RamSaw commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
Игра немного странная:
непонятно как менять тип снаряда
непонятно куда я сейчас стрельну, нарисуйте дуло, числа это конечно хорошо, но не наглядно
и я когда стреляю снаряд летит, а потом в рандомном месте исчезает
и цель невозможно убить по-моему, я в нее попадал, но она не умирала

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +        //g.getChildren().add(polygon1);
delete?

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +                -200.0, 600.0 });
-200?
что-то эти числа совсем странные, напишите либо комменты либо сгенрируйте точки с шагом, чтобы следующая хоть как-то была завязана на предыдущую. А то другой программист вынужден будет решать задачку "угадай следующее число по первым числам последовательности".

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +        if (x < 400) {
о нет, так не пойдет. Мне кажется меньше даже кода будет, если вы сделаете это в общем случае, а не с захардкоженными значениями.

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +    private Label viewAngle;
эта сущность не Cannon, а UI игры

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        viewCannon = new Circle(centerX, centerY + upY, 15);
не надо хардкодить радиус

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +    private final int upY = -10;
не очень понятно, что это такое

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        private boolean isSmall;
enum надо делать. Вы сейчас одним взмахом руки не сможете добавить еще один тип, а хотелось бы.

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        private boolean isAsleep;
из кода не очень понятно, что она значит.

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +            if (isAsleep) {
обычно если спишь, то обновление не происходит.

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Target.java
> +        return (x - centerX) * (x - centerX) + (y - centerY) * (y - centerY);
sqrt? видимо из-за этого цель никак не убить.

2019-05-31 11:58 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Target.java
> +        return (x - centerX) * (x - centerX) + (y - centerY) * (y - centerY);
В Point2D классе JavaFX уже есть все эти функции, советую на них перейти.

2019-05-31 12:07 UTC, MRedor commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
Ммм. Он у вас исчезает до того как долетел?

2019-05-31 12:09 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +                -200.0, 600.0 });
Там в условии прямо написано. Можно захардкодить ландшафт. Шо не так?

2019-05-31 12:11 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        private boolean isSmall;
Нет, не хотелось. Но добавлю

2019-05-31 12:13 UTC, MRedor commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
Поясните пожалуйста за нереализованную функциональность

2019-05-31 12:22 UTC, RamSaw commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
Да.

2019-05-31 12:23 UTC, RamSaw commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
Но не всегда. Иногда долетает

2019-05-31 12:24 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +                -200.0, 600.0 });
Я не знаю, что вам говорили на практике про задание, но мне кажется захардкодить это значит, что он может быть всегда один и тот же, то есть его генерировать не надо. Но на качество кода это не должно влиять.

2019-05-31 12:26 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        private boolean isSmall;
:)
Разницы же по сложности нет между двумя вариантами, но в одном случае код расширяем и поддерживаем, а в другой нет.

2019-05-31 12:26 UTC, RamSaw commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
Ну снаряд пропадает и я убить цель так и не смог, хотя попадал в неё.

2019-05-31 12:30 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +                -200.0, 600.0 });
Так, ок. И если это не менять, вы еще баллы снимете или уже достаточно?

2019-05-31 12:32 UTC, MRedor commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
Правда же, что вы не хотите чтоб я еще визуальную часть типа дула?

2019-05-31 13:16 UTC, RamSaw commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
ну дуло было бы неплохо :) это же не очень сложно кажется. Но хотя бы возможность убить цель надо предоставить пользователю.

2019-05-31 13:17 UTC, RamSaw commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +                -200.0, 600.0 });
ахах, я не знаю. Видимо, это уже Тимофей тогда решит.

2019-06-06 18:16 UTC, MRedor commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
по поводу jar. Говорят, это не обязательно фиксить. Правда?

2019-06-07 16:49 UTC, RamSaw commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
вообще некоторые ваши сокурсники справились без особых костылей это реализовать, но да ладно, пусть будет необязательно. Вы исправлять что-то будете в итоге?

2019-06-07 17:02 UTC, MRedor commented on Cannon/build.gradle
> +    mainClassName = 'me.mredor.hw.cannon.Main'
угу. кажется, сегодня еще можно

2019-06-07 19:12 UTC, MRedor commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
ну это прикол конечно. У меня при всех попытках долетает. Правда иногда в середине зависает (а иногда и в двух местах), но потом долетает.
При чем почему зависает совсем не понятно. Я не сама его двигаю, а отправляю лететь по кривой QuadCurve которая так-то заканчивается как раз где надо.

2019-06-09 08:17 UTC, RamSaw commented
@MRedor позовите когда исправите. И отпишитесь в комментах под каждым замечанием, которое вы пофиксили. Типа "Fixed". Я просто сейчас запустил и снаряди до сих пор исчезает.

2019-06-09 08:19 UTC, MRedor commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
Ну рил. Кажется, здесь проблема не во мне. 
Ну и как я уже сказала -- у меня он ни разу не исчез

2019-06-09 08:20 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        viewCannon = new Circle(centerX, centerY + upY, 15);
Fixed

2019-06-09 08:21 UTC, MRedor commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
Цель теперь убить легче

2019-06-09 08:21 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +                -200.0, 600.0 });
Fixed

2019-06-09 08:21 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +        //g.getChildren().add(polygon1);
Fixed

2019-06-09 08:22 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Background.java
> +        if (x < 400) {
Fixed

2019-06-09 08:22 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +    private final int upY = -10;
Fixed

2019-06-09 08:23 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        private boolean isSmall;
Fixed

2019-06-09 08:23 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +        private boolean isAsleep;
Fixed

2019-06-09 08:23 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Target.java
> +        return (x - centerX) * (x - centerX) + (y - centerY) * (y - centerY);
Fixed

2019-06-09 08:23 UTC, MRedor commented on Cannon/src/main/java/me/mredor/hw/cannon/Cannon.java
> +            if (isAsleep) {
Fixed

2019-06-09 08:38 UTC, MRedor commented
@RamSaw 
Так. Я не могу даже повторить ситуацию с пропаданием снаряда :(
Остальное +- исправила.
Можно обсудить сколько баллов можно поставить уже сейчас.

2019-06-10 08:25 UTC, jzuken commented
у меня, кстати, тоже иногда пропадает снаряд. и подлагивает временами, особенно когда вверх стрелять

2019-06-10 08:27 UTC, jzuken commented
12 баллов

2019-06-10 08:27 UTC, merged